development: &default
  adapter: sqlite3
  database: infinite_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: jppost_test

production:
  adapter: sqlite3
  database: infinite_production
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
